name: Cypress Testes

on: 
  workflow_dispatch:
    inputs: 
      cli:
        description: Run by cypress command line
        default: yarn cypress run

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest 
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: install dependencies
        run: npm install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
